[test]
coverage = true
coverageThreshold = 0.9
coveragePathIgnorePatterns = [
  "src/commands/utils/test-utils.ts",
  "src/commands/visualize/command.tsx",
  # Remove once we add integration tests that cover command action handlers
  "src/commands/generate/command.tsx"
]
